
    export const locations = [
        { id: 1, country: "Peru", state: "Amazonas" },
        { id: 2, country: "Peru", state: "Áncash" },
        { id: 3, country: "Peru", state: "Apurímac" },
        { id: 4, country: "Peru", state: "Arequipa" },
        { id: 5, country: "Peru", state: "Ayacucho" },
        { id: 6, country: "Peru", state: "Cajamarca" },
        { id: 7, country: "Peru", state: "Callao" },
        { id: 8, country: "Peru", state: "Cusco" },
        { id: 9, country: "Peru", state: "Huancavelica" },
        { id: 10, country: "Peru", state: "Huánuco" },
        { id: 11, country: "Peru", state: "Ica" },
        { id: 12, country: "Peru", state: "Junín" },
        { id: 13, country: "Peru", state: "La Libertad" },
        { id: 14, country: "Peru", state: "Lambayeque" },
        { id: 15, country: "Peru", state: "Lima" },
        { id: 16, country: "Peru", state: "Loreto" },
        { id: 17, country: "Peru", state: "Madre de Dios" },
        { id: 18, country: "Peru", state: "Moquegua" },
        { id: 19, country: "Peru", state: "Pasco" },
        { id: 20, country: "Peru", state: "Piura" },
        { id: 21, country: "Peru", state: "Puno" },
        { id: 22, country: "Peru", state: "San Martín" },
        { id: 23, country: "Peru", state: "Tacna" },
        { id: 24, country: "Peru", state: "Tumbes" },
        { id: 25, country: "Peru", state: "Ucayali" },
        { id: 26, country: "Mexico", state: "Aguascalientes" },
        { id: 27, country: "Mexico", state: "Baja California" },
        { id: 28, country: "Mexico", state: "Baja California Sur" },
        { id: 29, country: "Mexico", state: "Campeche" },
        { id: 30, country: "Mexico", state: "Chiapas" },
        { id: 31, country: "Mexico", state: "Chihuahua" },
        { id: 32, country: "Mexico", state: "Coahuila" },
        { id: 33, country: "Mexico", state: "Colima" },
        { id: 34, country: "Mexico", state: "Durango" },
        { id: 35, country: "Mexico", state: "Guanajuato" },
        { id: 36, country: "Mexico", state: "Guerrero" },
        { id: 37, country: "Mexico", state: "Hidalgo" },
        { id: 38, country: "Mexico", state: "Jalisco" },
        { id: 39, country: "Mexico", state: "México" },
        { id: 40, country: "Mexico", state: "Mexico City" },
        { id: 41, country: "Mexico", state: "Michoacán" },
        { id: 42, country: "Mexico", state: "Morelos" },
        { id: 43, country: "Mexico", state: "Nayarit" },
        { id: 44, country: "Mexico", state: "Nuevo León" },
        { id: 45, country: "Mexico", state: "Oaxaca" },
        { id: 46, country: "Mexico", state: "Puebla" },
        { id: 47, country: "Mexico", state: "Querétaro" },
        { id: 48, country: "Mexico", state: "Quintana Roo" },
        { id: 49, country: "Mexico", state: "San Luis Potosí" },
        { id: 50, country: "Mexico", state: "Sinaloa" },
        { id: 51, country: "Mexico", state: "Sonora" },
        { id: 52, country: "Mexico", state: "Tabasco" },
        { id: 53, country: "Mexico", state: "Tamaulipas" },
        { id: 54, country: "Mexico", state: "Tlaxcala" },
        { id: 55, country: "Mexico", state: "Veracruz" },
        { id: 56, country: "Mexico", state: "Yucatán" },
        { id: 57, country: "Mexico", state: "Zacatecas" }
    ];



export const taxiApps = [
    { name: 'Uber', icon: 'https://miro.medium.com/v2/resize:fit:1100/format:webp/1*xSNj61wUlEl2VGGnlmqELg.jpeg' },
    { name: 'Cabify', icon: 'https://cabify.com/favicon.ico' },
    { name: 'Lyft', icon: 'https://assets.website-files.com/5a1ce7bd9c7ab10001c4ab0d/5a1ce7bd9c7ab10001c4ad9f_lyft-favicon.png' },
    { name: 'DiDi', icon: 'https://website.didiglobal.com/favicon.ico' },
    { name: 'InDriver', icon: 'https://indriver.com/favicon.ico' },
    { name: 'Beat', icon: 'https://thebeat.co/favicon.ico' },
];
